### ISSUE TITLE
Pyhon error and ngrok 502 bad gateway error

### ISSUE THREAD

**Issue by mmackay911** [wayner9/alexa-solar-report#1]
I get the following error when running the python program:

Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "/home/pi/solar/pvout.py", line 8, in <module>
    from requests.packages.urllib3.exceptions import InsecurePlatformWarning, SNIMissingWarning
ImportError: cannot import name InsecurePlatformWarning

Also, ngrok running in a linux window returns 502 bad gateway errors when I ask Alexa anything like "ask solar report for power"

Any ideas?

**Comment by wayner9** [comment]
One other thing to try would be "pip install requests".

**Comment by mmackay911** [comment]
I #'d lines 8, 9 and 10 as you suggested and it works a treat. Thanks for your expertise.
